package main

import (
	"strings"
	"testing"
)

func TestGenerate(t *testing.T) {
	out, err := generate("testdata")
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		`kuhooks.Register("GoodHook", GoodHook)`,
		`kuhooks.Register("AliasedHook", AliasedHook)`,
	} {
		if !strings.Contains(out, want) {
			t.Fatalf("generated output missing %q:\n%s", want, out)
		}
	}
	if strings.Contains(out, "WrongParams") || strings.Contains(out, "WrongReturn") || strings.Contains(out, "NotAFunc") {
		t.Fatal("non-matching decls must be skipped")
	}
	if !strings.HasPrefix(out, "// Code generated by cmd/hookgen. DO NOT EDIT.") {
		t.Fatal("missing DO NOT EDIT header")
	}
}
