// hookgen scans a hooks/ directory for top-level functions matching the
// HookFunc signature and writes registry_gen.go registering each by name.
// Run via `go generate ./hooks` (wired into make dev / make build).
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// hooksImportPath is the contract package every hook signature refers to.
const hooksImportPath = "ku-crud/internal/hooks"

func generate(dir string) (string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return "", err
	}
	var names []string
	fset := token.NewFileSet()
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") || e.Name() == "registry_gen.go" {
			continue
		}
		f, err := parser.ParseFile(fset, filepath.Join(dir, e.Name()), nil, 0)
		if err != nil {
			return "", err
		}
		pkg := importLocalName(f)
		if pkg == "" {
			continue // file does not use the hooks contract
		}
		for _, d := range f.Decls {
			fn, ok := d.(*ast.FuncDecl)
			if !ok || fn.Recv != nil || fn.Type.TypeParams != nil {
				continue
			}
			if matchesSignature(fn.Type, pkg) {
				names = append(names, fn.Name.Name)
			}
		}
	}
	sort.Strings(names)
	var b strings.Builder
	b.WriteString("// Code generated by cmd/hookgen. DO NOT EDIT.\n\npackage hooks\n\n")
	if len(names) > 0 {
		b.WriteString("import kuhooks \"" + hooksImportPath + "\"\n\nfunc init() {\n")
		for _, n := range names {
			fmt.Fprintf(&b, "\tkuhooks.Register(%q, %s)\n", n, n)
		}
		b.WriteString("}\n")
	}
	return b.String(), nil
}

// importLocalName returns the identifier the file uses for the hooks
// contract package (alias or default "hooks"), or "" if not imported.
func importLocalName(f *ast.File) string {
	for _, imp := range f.Imports {
		if strings.Trim(imp.Path.Value, `"`) != hooksImportPath {
			continue
		}
		if imp.Name != nil {
			return imp.Name.Name
		}
		return "hooks"
	}
	return ""
}

// matchesSignature reports whether typ is
// func(context.Context, *P.HookContext, P.Event, P.RowPayload, json.RawMessage) (P.RowPayload, error)
// with P = pkg and json = encoding/json.
func matchesSignature(typ *ast.FuncType, pkg string) bool {
	params := typ.Params.List
	if len(params) != 5 || typ.Results == nil || len(typ.Results.List) != 2 {
		return false
	}
	if !isSel(params[0], "context", "Context") ||
		!isPtrSel(params[1], pkg, "HookContext") ||
		!isSel(params[2], pkg, "Event") ||
		!isSel(params[3], pkg, "RowPayload") ||
		!isSel(params[4], "json", "RawMessage") ||
		!isSel(typ.Results.List[0], pkg, "RowPayload") ||
		!isIdent(typ.Results.List[1], "error") {
		return false
	}
	return true
}

func isSel(f *ast.Field, pkg, name string) bool {
	sel, ok := f.Type.(*ast.SelectorExpr)
	if !ok || sel.Sel.Name != name {
		return false
	}
	id, ok := sel.X.(*ast.Ident)
	return ok && id.Name == pkg
}

func isPtrSel(f *ast.Field, pkg, name string) bool {
	star, ok := f.Type.(*ast.StarExpr)
	if !ok {
		return false
	}
	return isSel(&ast.Field{Type: star.X}, pkg, name)
}

func isIdent(f *ast.Field, name string) bool {
	id, ok := f.Type.(*ast.Ident)
	return ok && id.Name == name
}

func main() {
	dir := "."
	if len(os.Args) > 1 {
		dir = os.Args[1]
	}
	out, err := generate(dir)
	if err != nil {
		fmt.Fprintln(os.Stderr, "hookgen:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(filepath.Join(dir, "registry_gen.go"), []byte(out), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "hookgen:", err)
		os.Exit(1)
	}
}
