// Code generated by cmd/hookgen. DO NOT EDIT.

package hooks

import kuhooks "ku-crud/internal/hooks"

func init() {
	kuhooks.Register("LogAfterCreate", LogAfterCreate)
	kuhooks.Register("NormalizePrice", NormalizePrice)
}
