// Code generated by cmd/hookgen. DO NOT EDIT.

package hooks

import kuhooks "github.com/luthfi9251/ku-crud/core/hooks"

func init() {
	kuhooks.Register("LogAfterCreate", LogAfterCreate)
	kuhooks.Register("NormalizePrice", NormalizePrice)
}
